package metadata

import (
	"fmt"
	"gitlab.grandhoo.com/rock/rock-share/global/model/rds"
	"gitlab.grandhoo.com/rock/rock_v3/utils"
	"testing"
)

func Test_InitMetadata(t *testing.T) {
	rulesJson := []string{
		"{\"TableId\":\"1698309991919\",\"Ree\":\"tabLoan(t0)^tabLoan(t1)^t0.code=t1.code->t0.applicant=t1.applicant\",\"LhsPredicates\":[{\"PredicateStr\":\"t0.code=t1.code\",\"LeftColumn\":{\"TableId\":\"1698309991919\",\"TableAlias\":\"t0\",\"ColumnId\":\"code\",\"ColumnType\":\"string\"},\"RightColumn\":{\"TableId\":\"1698309991919\",\"TableAlias\":\"t1\",\"ColumnId\":\"code\",\"ColumnType\":\"string\"},\"GroupByColumn\":null,\"ConstantValue\":null,\"ConstantIndexValue\":0,\"SymbolType\":\"=\",\"PredicateType\":2,\"UDFName\":\"\",\"Threshold\":0,\"Support\":0}],\"LhsColumns\":[{\"TableId\":\"1698309991919\",\"TableAlias\":\"t0\",\"ColumnId\":\"code\",\"ColumnType\":\"string\"},{\"TableId\":\"1698309991919\",\"TableAlias\":\"t1\",\"ColumnId\":\"code\",\"ColumnType\":\"string\"}],\"Rhs\":{\"PredicateStr\":\"t0.applicant=t1.applicant\",\"LeftColumn\":{\"TableId\":\"1698309991919\",\"TableAlias\":\"t0\",\"ColumnId\":\"applicant\",\"ColumnType\":\"string\"},\"RightColumn\":{\"TableId\":\"1698309991919\",\"TableAlias\":\"t1\",\"ColumnId\":\"applicant\",\"ColumnType\":\"string\"},\"GroupByColumn\":null,\"ConstantValue\":null,\"ConstantIndexValue\":0,\"SymbolType\":\"=\",\"PredicateType\":3,\"UDFName\":\"\",\"Threshold\":0,\"Support\":0},\"RhsColumn\":{\"TableId\":\"1698309991919\",\"TableAlias\":\"t0\",\"ColumnId\":\"applicant\",\"ColumnType\":\"string\"},\"CR\":0,\"FTR\":0,\"RuleType\":0,\"XSupp\":0,\"XySupp\":0,\"XSatisfyCount\":0,\"CfdStatus\":0}",
		"{\"TableId\":\"1701844220997\",\"Ree\":\"tabLoan(t0)^tabLoan(t1)^t0.loan_application=t1.loan_application->t0.company=t1.company\",\"LhsPredicates\":[{\"PredicateStr\":\"t0.loan_application=t1.loan_application\",\"LeftColumn\":{\"TableId\":\"1701844220997\",\"TableAlias\":\"t0\",\"ColumnId\":\"loan_application\",\"ColumnType\":\"string\"},\"RightColumn\":{\"TableId\":\"1701844220997\",\"TableAlias\":\"t1\",\"ColumnId\":\"loan_application\",\"ColumnType\":\"string\"},\"GroupByColumn\":null,\"ConstantValue\":null,\"ConstantIndexValue\":0,\"SymbolType\":\"=\",\"PredicateType\":2,\"UDFName\":\"\",\"Threshold\":0,\"Support\":0}],\"LhsColumns\":[{\"TableId\":\"1701844220997\",\"TableAlias\":\"t0\",\"ColumnId\":\"loan_application\",\"ColumnType\":\"string\"},{\"TableId\":\"1701844220997\",\"TableAlias\":\"t1\",\"ColumnId\":\"loan_application\",\"ColumnType\":\"string\"}],\"Rhs\":{\"PredicateStr\":\"t0.company=t1.company\",\"LeftColumn\":{\"TableId\":\"1701844220997\",\"TableAlias\":\"t0\",\"ColumnId\":\"company\",\"ColumnType\":\"string\"},\"RightColumn\":{\"TableId\":\"1701844220997\",\"TableAlias\":\"t1\",\"ColumnId\":\"company\",\"ColumnType\":\"string\"},\"GroupByColumn\":null,\"ConstantValue\":null,\"ConstantIndexValue\":0,\"SymbolType\":\"=\",\"PredicateType\":3,\"UDFName\":\"\",\"Threshold\":0,\"Support\":0},\"RhsColumn\":{\"TableId\":\"1701844220997\",\"TableAlias\":\"t0\",\"ColumnId\":\"company\",\"ColumnType\":\"string\"},\"CR\":0,\"FTR\":0,\"RuleType\":0,\"XSupp\":0,\"XySupp\":0,\"XSatisfyCount\":0,\"CfdStatus\":0}",
		"{\"TableId\":\"1698041310857\",\"Ree\":\"tabLoan_Application(t0)^tabLoan(t2)^tabLoan_Disbursement(t4)^t0.name=t2.loan_application^t2.name=t4.against_loan->t0.loan_amount=t4.amount_paid\",\"LhsPredicates\":[{\"PredicateStr\":\"t0.name=t2.loan_application\",\"LeftColumn\":{\"TableId\":\"1698041310857\",\"TableAlias\":\"\",\"ColumnId\":\"name\",\"ColumnType\":\"string\"},\"RightColumn\":{\"TableId\":\"1698032819076\",\"TableAlias\":\"\",\"ColumnId\":\"loan_application\",\"ColumnType\":\"string\"},\"GroupByColumn\":null,\"ConstantValue\":null,\"ConstantIndexValue\":0,\"SymbolType\":\"=\",\"PredicateType\":2,\"UDFName\":\"\",\"Threshold\":0,\"Support\":0},{\"PredicateStr\":\"t2.name=t4.against_loan\",\"LeftColumn\":{\"TableId\":\"1698032819076\",\"TableAlias\":\"\",\"ColumnId\":\"name\",\"ColumnType\":\"string\"},\"RightColumn\":{\"TableId\":\"1698041331359\",\"TableAlias\":\"\",\"ColumnId\":\"against_loan\",\"ColumnType\":\"string\"},\"GroupByColumn\":null,\"ConstantValue\":null,\"ConstantIndexValue\":0,\"SymbolType\":\"=\",\"PredicateType\":2,\"UDFName\":\"\",\"Threshold\":0,\"Support\":0}],\"LhsColumns\":[{\"TableId\":\"1698041310857\",\"TableAlias\":\"\",\"ColumnId\":\"name\",\"ColumnType\":\"string\"},{\"TableId\":\"1698032819076\",\"TableAlias\":\"\",\"ColumnId\":\"loan_application\",\"ColumnType\":\"string\"},{\"TableId\":\"1698032819076\",\"TableAlias\":\"\",\"ColumnId\":\"name\",\"ColumnType\":\"string\"},{\"TableId\":\"1698041331359\",\"TableAlias\":\"\",\"ColumnId\":\"against_loan\",\"ColumnType\":\"string\"}],\"Rhs\":{\"PredicateStr\":\"t0.loan_amount=t4.amount_paid\",\"LeftColumn\":{\"TableId\":\"1698041310857\",\"TableAlias\":\"\",\"ColumnId\":\"loan_amount\",\"ColumnType\":\"float64\"},\"RightColumn\":{\"TableId\":\"1698041331359\",\"TableAlias\":\"\",\"ColumnId\":\"amount_paid\",\"ColumnType\":\"float64\"},\"GroupByColumn\":null,\"ConstantValue\":null,\"ConstantIndexValue\":0,\"SymbolType\":\"=\",\"PredicateType\":3,\"UDFName\":\"\",\"Threshold\":0,\"Support\":0},\"RhsColumn\":{\"TableId\":\"1698041310857\",\"TableAlias\":\"\",\"ColumnId\":\"loan_amount\",\"ColumnType\":\"float64\"},\"CR\":0,\"FTR\":0,\"RuleType\":0,\"XSupp\":0,\"XySupp\":0,\"XSatisfyCount\":0,\"CfdStatus\":0}",
	}
	ruleMap := make(map[int]*rds.Rule, len(rulesJson))
	for ruleId, ruleJson := range rulesJson {
		rule := utils.GetFormatRule(ruleJson)
		ruleMap[ruleId] = &rule
	}

	InitTaskMetadata(100000000, ruleMap)
	for taskId, metadata := range taskMetadata {
		fmt.Printf("任务:%s, metadata:%v", taskId, *metadata)
	}
}
